name: Run PythonScript to get latest top 20 GH repos and write to repos.txt file
   
on:
  schedule:
    - cron: '0 7 * * 1'  # 7 AM UTC every Monday
  workflow_dispatch:


jobs:
  run_script:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.8

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install requests

    - name: Run Python script
      run: python GH-scrape-popular-repos.py

    - name: Upload gh-scrape-top-20-repos.txt as artifact
      uses: actions/upload-artifact@v2
      with:
        name: gh-scrape-top-20-repos
        path: gh-scrape-top-20-repos.txt

    - name: Configure Git
      run: |
        git config --global user.email "github-actions@github.com"
        git config --global user.name "GitHub Actions"

    - name: Checkout RepoUpdatePR branch
      run: git checkout -B RepoUpdatePR origin/main

    - name: Apply changes from repos.txt
      run: cat gh-scrape-top-20-repos.txt >> repos_from_action.txt  # Append the contents of repos.txt to an existing file (replace with your logic)

    - name: Commit and push changes
      run: |
        git add repos_from_action.txt
        git commit -m "Update repositories from GitHub Actions"
        git push origin GH-Top-20-Repo-List-Update-PR

    - name: Create Pull Request
      uses: peter-evans/create-pull-request@v3
      with:
        token: ${{ secrets.GITHUB_SECRET }}
        branch: GH-Top-20-Repo-List-Update-PR
        base: main
        title: "Update repositories from GitHub Actions"
        body: "This pull request updates the repositories from the GitHub Actions workflow."
