name: Run Python Script

on:
  push:
    branches:
      - main  # Change to the default branch name of your repository

jobs:
  run_script:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.8

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt  pip install requests

    - name: Run Python script
      run: python gh-api-call-for-repo-list.py
